<a href="https://colab.research.google.com/github/fadi212/Complete-Python-Bootcamp/blob/master/Adults.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

In [0]:
cols = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','class']
df = pd.read_csv('adults.train.txt', names = cols)

In [4]:
df.shape

(11416, 15)

In [5]:
df.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
education-num     float64
marital-status     object
occupation         object
relationship       object
race               object
sex                object
capital-gain      float64
capital-loss      float64
hours-per-week    float64
native-country     object
class              object
dtype: object

In [6]:
#checking the missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         1
education-num     1
marital-status    1
occupation        1
relationship      1
race              1
sex               1
capital-gain      1
capital-loss      1
hours-per-week    1
native-country    1
class             1
dtype: int64

In [7]:
#dropping the missing value observations
df = df.dropna()
df.shape

(11415, 15)

In [8]:
df['class'][df['class'].str.contains("<") == True] = 0
df['class'][df['class'].str.contains("<") == False] = 1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [9]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors           13.0   
1   50   Self-emp-not-inc   83311   Bachelors           13.0   
2   38            Private  215646     HS-grad            9.0   
3   53            Private  234721        11th            7.0   
4   28            Private  338409   Bachelors           13.0   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country class  
0        2174.0           0.0            40.0   United-States     0  
1           0.0           0.0            13.0   United-States     0  
2           0.0           0.0            40.0   United-States     0  
3           0.0           0.0            40.0   United-States     0  
4           0.0           0.0            40.0            Cuba     0

In [10]:
df['class'].value_counts()

0    8694
1    2721
Name: class, dtype: int64

In [0]:
df['class'] = df['class'].astype('int64')

In [0]:
y = df['class'].values

In [13]:
df = df.iloc[:,:-1]
df.shape

(11415, 14)

In [0]:
catigorical_df = df.select_dtypes(['object'])

In [0]:
int_and_float_df = df.select_dtypes(['int64','float64'])

In [16]:
int_and_float_df.shape

(11415, 6)

In [17]:
catigorical_df.shape

(11415, 8)

In [0]:
dumies_df = pd.get_dummies(catigorical_df)

In [0]:
X_df = pd.concat([dumies_df, int_and_float_df], axis=1)

In [20]:
X_df.shape

(11415, 107)

In [0]:
#avoiding dummy variable trap
X_df = X_df.iloc[:,1:]

In [0]:
X = X_df.values

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [0]:
lr = LogisticRegression(solver='lbfgs', max_iter=200)
svm = SVC(gamma='auto')
nb = GaussianNB()

In [25]:
print("Cross Validation score for Logitic Regression is "+ str(cross_val_score(lr,X,y,cv=10).mean()))
print("Cross Validation score for SVC is "+ str(cross_val_score(svm,X,y,cv=10).mean()))
print("Cross Validation score for Naive Bayes is "+ str(cross_val_score(nb,X,y,cv=10).mean()))

Cross Validation score for Logitic Regression is 0.7999134771938923
Cross Validation score for SVC is 0.758299132636248
Cross Validation score for Naive Bayes is 0.7966720881576006


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state=42)

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
nb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [34]:
confusion_matrix(y_train, nb.predict(X_train))

array([[ 872, 5644],
       [  28, 2017]])

In [40]:
print(classification_report(y_train, nb.predict(X_train)))

              precision    recall  f1-score   support

           0       0.97      0.13      0.24      6516
           1       0.26      0.99      0.42      2045

   micro avg       0.34      0.34      0.34      8561
   macro avg       0.62      0.56      0.33      8561
weighted avg       0.80      0.34      0.28      8561



In [41]:
accuracy_score(y_train, nb.predict(X_train))

0.33746057703539306

In [43]:
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
confusion_matrix(y_train, svm.predict(X_train))

array([[6190,  326],
       [ 843, 1202]])

In [45]:
svm.score(X_train,y_train)

0.8634505314799673

In [46]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
confusion_matrix(y_train, lr.predict(X_train))

array([[6071,  445],
       [ 836, 1209]])